"""drop is_shareable from blocks

Revision ID: 043ed758be15
Revises: dd1e8df54032
Create Date: 2026-06-13 22:45:10.121152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043ed758be15'
down_revision: Union[str, Sequence[str], None] = 'dd1e8df54032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'is_shareable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('is_shareable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
