"""create user permissions table

Revision ID: 106add0641e6
Revises: 84a6e7add31b
Create Date: 2026-08-21 19:33:05.064229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106add0641e6'
down_revision: Union[str, Sequence[str], None] = '84a6e7add31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_permissions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
