"""block vaddr nullable

Revision ID: 156b74a390bf
Revises: 73b700b27334
Create Date: 2026-06-16 11:34:50.781785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156b74a390bf'
down_revision: Union[str, Sequence[str], None] = '73b700b27334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'vaddr',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'vaddr',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
