"""partial indexes for sweeper

Revision ID: 508f1b747653
Revises: 156854ff3eed
Create Date: 2026-08-17 12:53:01.731049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508f1b747653'
down_revision: Union[str, Sequence[str], None] = '156854ff3eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tests_pending_uploaded_at', 'tests', ['uploaded_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('ix_validations_pending_requested_at', 'validation_results', ['requested_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validations_pending_requested_at', table_name='validation_results', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_tests_pending_uploaded_at', table_name='tests', postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
