"""Allow null part id to Block

Revision ID: 6e3379b23cf6
Revises: 9cc82ee1e847
Create Date: 2025-11-26 20:23:33.200552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3379b23cf6'
down_revision: Union[str, Sequence[str], None] = '9cc82ee1e847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'partition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'partition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
