"""Add safety_zone_before/after_unmapped to Block

Revision ID: 726547b1c706
Revises: b9a5dada4b8d
Create Date: 2025-11-26 20:12:57.820349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726547b1c706'
down_revision: Union[str, Sequence[str], None] = 'b9a5dada4b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('safety_zone_before_unmapped', sa.Boolean(), nullable=False))
    op.add_column('blocks', sa.Column('safety_zone_after_unmapped', sa.Boolean(), nullable=False))
    op.alter_column('blocks', 'safety_zone_before',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False,
               postgresql_using='safety_zone_before::integer')
    op.alter_column('blocks', 'safety_zone_after',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False,
               postgresql_using='safety_zone_after::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'safety_zone_after',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='safety_zone_after::integer')
    op.alter_column('blocks', 'safety_zone_before',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='safety_zone_before::integer')
    op.drop_column('blocks', 'safety_zone_after_unmapped')
    op.drop_column('blocks', 'safety_zone_before_unmapped')
    # ### end Alembic commands ###
