"""block exclusive ownership: nullable module_id, drop is_shareable

Revision ID: 73b700b27334
Revises: 043ed758be15
Create Date: 2026-06-14 21:46:27.195458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b700b27334'
down_revision: Union[str, Sequence[str], None] = '043ed758be15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint(
        "ck_block_single_owner",
        "blocks",
        "(module_id IS NULL) <> (partition_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_block_single_owner", "blocks", type_="check")
    op.alter_column('blocks', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
