"""validation lifecycle

Revision ID: 95fefff1c894
Revises: a06a411f81fe
Create Date: 2026-07-03 14:40:06.584976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95fefff1c894'
down_revision: Union[str, Sequence[str], None] = 'a06a411f81fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    validationstatus = postgresql.ENUM(
        'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='validationstatus'
    )
    validationstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('validation_results', sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='validationstatus'), nullable=False, server_default='PENDING'))
    op.alter_column('validation_results', 'valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('validation_results', 'schema_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('validation_results', 'checker_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('validation_results', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('validation_results', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('validation_results', 'checker_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('validation_results', 'schema_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('validation_results', 'valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('validation_results', 'status')
    sa.Enum(name='validationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
