"""add models yaml parser

Revision ID: b9a5dada4b8d
Revises: 12d358ae056a
Create Date: 2025-11-26 19:49:20.899352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a5dada4b8d'
down_revision: Union[str, Sequence[str], None] = '12d358ae056a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSED', 'ERROR', name='teststatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_name'), 'tests', ['name'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_space_base', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=False)
    op.create_table('partitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partitions_name'), 'partitions', ['name'], unique=False)
    op.create_index(op.f('ix_partitions_space_id'), 'partitions', ['space_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('access', sa.String(), nullable=False),
    sa.Column('align', sa.String(), nullable=False),
    sa.Column('cache_policy', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('init_file', sa.String(), nullable=True),
    sa.Column('init_stage', sa.String(), nullable=True),
    sa.Column('init_type', sa.String(), nullable=True),
    sa.Column('is_contiguous', sa.Boolean(), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('is_shareable', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('no_shadow', sa.Boolean(), nullable=False),
    sa.Column('paddr', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('vaddr', sa.Integer(), nullable=False),
    sa.Column('shadow_offset', sa.Integer(), nullable=True),
    sa.Column('shadow_scale', sa.Integer(), nullable=True),
    sa.Column('shadow_type', sa.String(), nullable=True),
    sa.Column('safety_zone_before', sa.String(), nullable=True),
    sa.Column('safety_zone_after', sa.String(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('partition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['partition_id'], ['partitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_name'), 'blocks', ['name'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paddr', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('vaddr', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    op.drop_index(op.f('ix_blocks_name'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_partitions_space_id'), table_name='partitions')
    op.drop_index(op.f('ix_partitions_name'), table_name='partitions')
    op.drop_table('partitions')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_tests_name'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
