"""add uploaded_by to TestCase

Revision ID: c3b5a7078096
Revises: 156b74a390bf
Create Date: 2026-06-16 15:30:50.649018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b5a7078096'
down_revision: Union[str, Sequence[str], None] = '156b74a390bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('uploaded_by_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tests', 'users', ['uploaded_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'uploaded_by_id')
    # ### end Alembic commands ###
