"""memory allocator domain: platforms, tags, validations, artifacts

Revision ID: dd1e8df54032
Revises: aa5f17d93943
Create Date: 2026-06-10 18:01:28.253822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1e8df54032'
down_revision: Union[str, Sequence[str], None] = 'aa5f17d93943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmu_family', sa.String(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_mmu_family'), 'platforms', ['mmu_family'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('test_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('CONFIG', 'SHARED_GROUPS', 'INPUT_CONSTRAINTS', 'INPUT_ARCH', 'OUTPUT_ARCH', 'OUTPUT_VDEFINITIONS', 'LOG', 'STATUS', name='artifactkind'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case_tag',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'tag_id')
    )
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checker_version', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tests', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.add_column('tests', sa.Column('module_count', sa.Integer(), nullable=False))
    op.add_column('tests', sa.Column('block_count', sa.Integer(), nullable=False))
    op.add_column('tests', sa.Column('kernel_entry_count', sa.Integer(), nullable=False))
    op.add_column('tests', sa.Column('user_entry_count', sa.Integer(), nullable=False))
    op.create_foreign_key("fk_tests_platform_id", 'tests', 'platforms', ['platform_id'], ['id'])
    op.add_column('users', sa.Column('created_at',sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.alter_column('tests', 'uploaded_at', type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_constraint("fk_tests_platform_id", 'tests', type_='foreignkey')
    op.drop_column('tests', 'user_entry_count')
    op.drop_column('tests', 'kernel_entry_count')
    op.drop_column('tests', 'block_count')
    op.drop_column('tests', 'module_count')
    op.drop_column('tests', 'platform_id')
    op.drop_table('validation_results')
    op.drop_table('test_case_tag')
    op.drop_table('test_artifacts')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_platforms_mmu_family'), table_name='platforms')
    op.drop_table('platforms')
    sa.Enum(name='artifactkind').drop(op.get_bind())
    op.alter_column('tests', 'uploaded_at', type_=sa.DateTime())
    # ### end Alembic commands ###
